apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-app
  labels:
    app: nginx
    version: "1.14.2"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
