apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: my-app
type: Opaque
stringData:
  password: "adampassword123"   
  #When the secret is created, values in stringData are encoded and moved to the data field