#ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: my-app
spec:
  type: ClusterIP
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
#NodePort Service
#run kubectl expose deployment httpd-deployment --name= httpd-nodeport -n my-app --type= NodePort --port= 80 --target-port= 80
apiVersion: v1
kind: Service
metadata:
  name: httpd-nodeport
  namespace: my-app
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080